Refactoring /etc/init.d/docker

diff --git a/overlay/etc/init.d/docker b/overlay/etc/init.d/docker
--- a/overlay/etc/init.d/docker
+++ b/overlay/etc/init.d/docker
@@ -46,9 +46,9 @@ start() {
 
   if ${DOCKER_SWITCHING} ; then
     for i in docker docker-containerd docker-containerd-ctr docker-containerd-shim docker-runc; do
-      rm -f /opt/bin/$i
-      if [ -f ${DOCKER_BIN_DIR}/$i ]; then
-        ln -s ${DOCKER_BIN_DIR}/$i /opt/bin/$i
+      rm -f "/opt/bin/$i"
+      if [ -f "${DOCKER_BIN_DIR}/$i" ]; then
+        ln -s "${DOCKER_BIN_DIR}/$i" "/opt/bin/$i"
       fi
     done
     sed -i "s/Docker version.*/$(${DOCKER} -v)/" /etc/motd
@@ -59,9 +59,9 @@ start() {
   logger -s -p user.info -t "docker[$$]" "Starting Docker daemon ${params}"
   echo "Starting Docker daemon ${params}" >> "${DOCKER_LOGFILE}"
   if [ "$$" == "1" ]; then
-    eval "exec ${DOCKER} daemon ${params} >> \"${DOCKER_LOGFILE}\" 2>&1"
+    eval "exec ${DOCKER} ${DOCKER_DAEMON_COMMAND} ${params} >> \"${DOCKER_LOGFILE}\" 2>&1"
   else
-    eval "${DOCKER} daemon ${params} >> \"${DOCKER_LOGFILE}\" 2>&1 &"
+    eval "${DOCKER} ${DOCKER_DAEMON_COMMAND} ${params} >> \"${DOCKER_LOGFILE}\" 2>&1 &"
   fi
 }
 
@@ -116,17 +116,13 @@ status() {
 download() {
   local version="${1/#v/}"
 
-  DOCKER_BIN_DIR="${DOCKER}-v${version}"
-  DOCKER_BIN="${DOCKER_BIN_DIR}/docker"
+  DOCKER_BIN_DIR="/opt/docker/v${version}"
 
-  local multi_binaries=true
   local versions=($(echo ${version} | tr -s '.' ' '))
   if [[ ${versions[0]} -lt 1 ]]; then
     echo "Docker v${version} is too old." >&2 && exit 1
   elif [[ (${versions[0]} -eq 1) && (${versions[1]} -lt 8) ]]; then
     echo "Docker v${version} is too old." >&2 && exit 1
-  elif [[ (${versions[0]} -eq 1) && (${versions[1]} -lt 11) ]]; then
-    multi_binaries=false
   fi
 
   local base_url="https://get.docker.io/builds/Linux/x86_64"
@@ -134,39 +130,32 @@ download() {
     base_url="https://test.docker.com/builds/Linux/x86_64"
   fi
 
-  if [ ! -f ${DOCKER_BIN} ]; then
+  if [ ! -f "${DOCKER_BIN_DIR}/${DOCKER_DAEMON}" ]; then
     echo -n "Downloading v${version} ..."
-    trap "rm -rf ${DOCKER_BIN_DIR}" ERR
-    mkdir -p ${DOCKER_BIN_DIR}
-
-    if ${multi_binaries} ; then
-      wget -qO- ${base_url}/docker-${version}.tgz | tar zxf - -C ${DOCKER_BIN_DIR} 2>/dev/null
-      if [ -d ${DOCKER_BIN_DIR}/usr ]; then
-        mv -f ${DOCKER_BIN_DIR}/usr/local/bin/* ${DOCKER_BIN_DIR}
-        rm -rf ${DOCKER_BIN_DIR}/usr
-      fi
-    else
-      wget -qO ${DOCKER_BIN} ${base_url}/docker-${version}
-      [ -f ${DOCKER_BIN} ] && chmod +x ${DOCKER_BIN}
+    trap "rm -rf \"${DOCKER_BIN_DIR}\"" ERR
+    mkdir -p "${DOCKER_BIN_DIR}"
+    wget -qO- "${base_url}/docker-${version}.tgz" | tar zxf - -C "${DOCKER_BIN_DIR}" 2>/dev/null
+    if [ -d "${DOCKER_BIN_DIR}/usr/local/bin" ]; then
+      mv -f "${DOCKER_BIN_DIR}/usr/local/bin"/* "${DOCKER_BIN_DIR}"
+      rm -rf "${DOCKER_BIN_DIR}/usr"
     fi
-
-    [ -f ${DOCKER_BIN} ] || echo -n " not found."
+    [ -f "${DOCKER_BIN_DIR}/${DOCKER_DAEMON}" ] || echo -n " not found."
     echo
   fi
 }
 
-readonly DOCKER="/opt/bin/docker"
+DOCKER_DAEMON="docker"
+DOCKER_DAEMON_COMMAND="daemon"
+DOCKER="/opt/bin/${DOCKER_DAEMON}"
 DOCKER_BIN_DIR="/usr/bin"
-DOCKER_BIN="${DOCKER_BIN_DIR}/docker"
-if [ ! -f ${DOCKER} ]; then
+if [ ! -f "${DOCKER}" ]; then
   mkdir -p /opt/bin
-  ln -s ${DOCKER_BIN} ${DOCKER}
+  ln -s "${DOCKER_BIN_DIR}/${DOCKER_DAEMON}" "${DOCKER}"
 fi
 DOCKER_SWITCHING=false
 if [ -n "$2" ]; then
   if [ "$2" = "default" ]; then
     DOCKER_BIN_DIR="/usr/bin"
-    DOCKER_BIN="${DOCKER_BIN_DIR}/docker"
   else
     version=$2
     if [ "${version}" = "latest" ]; then
@@ -174,7 +163,7 @@ if [ -n "$2" ]; then
         | awk -F'"' '/tag_name/ { print $4 }')
     fi
     download ${version}
-    [ ! -f ${DOCKER_BIN} ] && exit 1
+    [ ! -f "${DOCKER_BIN_DIR}/${DOCKER_DAEMON}" ] && exit 1
   fi
   DOCKER_SWITCHING=true
 fi
